### ISSUE TITLE
•	ExtraCreditB – 5 pts for built-in help menu (type “help” displays all commands and how to use them)

### ISSUE THREAD

**Issue by TFlexSoom** [andrew-pa/TextExcel#2]
I can probably do this but the decision is should we make this a function like sum or a check like quit. Either way it would be nice to eventually pull out a detailed list of what our program can actually do.

**Comment by andrew-pa** [comment]
Ah the help system... Function is better, but we also need some kind of system to organize all the help as it's rather complicated 

Sent from Outlook Mobile

From: TFlexSoom

Sent: Friday, February 12, 7:03 PM

Subject: [TextExcel] • ExtraCreditB – 5 pts for built-in help menu (type “help” displays all commands and how to use them) (#2)

To: andrew-pa/TextExcel

I can probably do this but the decision is should we make this a function like sum or a check like quit. Either way it would be nice to eventually pull out a detailed list of what our program can actually do.
